version: '3'

services:
  db:
    image: mongo
    networks:
      - backend-network

  backend:
    build: ./backend
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - frontend-network
    depends_on:
      - backend

networks:
  frontend-network:
  backend-network: